### ISSUE TITLE
Provide an example

### ISSUE THREAD

**Issue by nlohmann** [bjornus/documentator#1]
An example project with the generated documentation would help a lot. I would not download and test the tool without knowing what the result looks like.

**Comment by szewczukk** [comment]
Example code is in example folder, and otuput of that code is in output folder
https://github.com/bjornus/documentator/tree/master/example
https://github.com/bjornus/documentator/tree/master/output

**Comment by nlohmann** [comment]
That's not really an example... I would expect a small C++ project. Furthermore, it would be great if you could serve the output somewhere so one does not need to clone your repo just to have a look.

**Comment by szewczukk** [comment]
Ok, i will create something like example project :) Thanks a lot!
